part_1:
  description:
  - Relationship (You are the Petitioner. Your relative is the Beneficiary)
  1:
  - I am filing this petition for my (Select only one box)
  - Spouse
  - Parent
  - Brother/Sister
  - Child
  2:
  - If you are filing this petition for your child or parent, select the box that describes your relationship (Select only one box)
  - child_married_parents
  - stepchild/stepparent
  - child_unmarried_parents
  - child_adopted
  3:
  - If the beneficiary is your brother/sister, are you related by adoption?
  - yes
  - no
  4:
  - Did you gain lawful permanent resident status or citizenship through adoption?
  - yes
  - no

part_2:
  part_description:
  - Information About You (Petitioner)
  1:
  - Alien Registration Number(A-Number)(if any)
  - alien_registration_number
  2:
  - USCIS Online Account Number (if any)
  - uscis_account_number
  3:
  - U.S. Social Security Number (if any)
  - ssn
  section_description_1:
  - Your Full Name
  4a:
  - Family Name (Last Name)
  - last_name
  4b:
  - Given Name (First Name)
  - first_name
  4c:
  - Middle Name
  - middle_name
  section_description_2:
  - Other Names Used (if any)
  5a:
  - last_name
  5b:
  - first_name
  5c:
  - middle_name
  section_description_3:
  - Other Information
  6:
  - city_town_village_of_birth
  7:
  - country_of_birth
  8:
  - dob_mm_dd_yyyy
  9:
  - sex
  section_description_4:
  - Mailing Address
  10a:
  - in_care_of_name
  10b:
  - street_number_and_name
  10c:
  - apt
  - ste
  - floor
  10d:
  - city_or_town
  10e:
  - state
  10f:
  - zipcode
  10g:
  - province
  10h:
  - postalcode
  10i:
  - country
  11:
  - mailing_and_physical_same
  section_description_5:
  - Address History
  12a:
  - street_number_and_name
  12b:
  - apt
  - ste
  - floor
  12c:
  - city_or_town
  12d:
  - state
  12e:
  - zipcode
  12f:
  - province
  12g:
  - postalcode
  12h:
  - country
  13a:
  - date_from
  13b:
  - date_to
  14a:
  - street_number_and_name
  14b:
  - apt
  - ste
  - floor
  14c:
  - city_or_town
  14d:
  - state
  14e:
  - zipcode
  14f:
  - province
  14g:
  - postalcode
  14h:
  - country
  15a:
  - date_from
  15b:
  - date_to
  section_description_6:
  - Your Marital Information
  16:
  - num_times_married
  17:
  - Single, Never Married
  - Married
  - Divorced
  - Widowed
  - Separated
  - Annulled
  18:
  - date_of_current_marriage
  section_description_7:
  - Place of Your Current Marriage (if married)
  19a:
  - city_or_town
  19b:
  - state
  19c:
  - province
  19d:
  - country
  section_description_8:
  - Names of All Your Spouses, Spouse 1 first, then all prior (if any)
  20a:
  - last_name
  20b:
  - first_name
  20c:
  - middle_name
  21:
  - date_marriage_ended
  22a:
  - last_name
  22b:
  - first_name
  22c:
  - middle_name
  23:
  - date_marriage_ended
  section_description_9:
  - Information About Your Parents
  24a:
  - last_name
  24b:
  - first_name
  24c:
  - middle_name
  25:
  - dob
  26:
  - male
  - female
  27:
  - country_of_birth
  28:
  - city_town_village_of_residence
  29:
  - country_of_residence
  30a:
  - last_name
  30b:
  - first_name
  30c:
  - middle_name
  31:
  - dob
  32:
  - male
  - female
  33:
  - country_of_birth
  34:
  - city_town_village_of_residence
  35:
  - country_of_residence
  section_description_10:
  - Additional Information About You (Petitioner)
  36:
  - us_citizen
  - lawful_permanent_resident
  37:
  - birth_in_the_us
  - naturalization
  - parents
  38:
  - yes
  - no
  39a:
  - certificate_number
  39b:
  - place_of_issuance
  39c:
  - date_of_issuance
  40a:
  - class_of_admission
  40b:
  - date_of_admission
  40c:
  - city_or_town
  40d:
  - state
  41:
  - yes
  - no
  section_description_11:
  - Employment History
  42:
  - name_of_employer_company
  43a:
  - street_number_and_name
  43b:
  - apt
  - ste
  - floor
  43c:
  - city_or_town
  43d:
  - state
  43e:
  - zipcode
  43f:
  - province
  43g:
  - postalcode
  43h:
  - country
  44:
  - your_occupation
  45a:
  - date_from
  45b:
  - date_to
  46:
  - name_of_employer_company
  47a:
  - street_number_and_name
  47b:
  - apt
  - ste
  - floor
  47c:
  - city_or_town
  47d:
  - state
  47e:
  - zipcode
  47f:
  - province
  47g:
  - postalcode
  47h:
  - country
  48:
  - your_occupation
  49a:
  - date_from
  49b:
  - date_to
part_3:
  description:
  - Biographic Information
  1:
  - ethnicity
  2:
  - race
  3:
  - height
  4:
  - weight
  5:
  - eye_color
  6:
  - hair_color
part_4:
  description:
  - Information About Beneficiary
  1:
  - alien_registration_number
  2:
  - uscis_account_number
  3:
  - ssn
  section_description_1:
  - Beneficiary's Full Name
  4a:
  - last_name
  4b:
  - first_name
  4c:
  - middle_name
  section_description_2:
  - Other Names Used (if any)
  5a:
  - last_name
  5b:
  - first_name
  5c:
  - middle_name
  section_description_3:
  - Other Information About Beneficiary
  6:
  - city_town_village_of_birth
  7:
  - country_of_birth
  8:
  - dob_mm_dd_yyyy
  9:
  - sex
  10:
  - has_anyone_filed_a_petition_for_you
  section_description_4:
  - Beneficiary's Physical Address
  11a:
  - street_number_and_name
  11b:
  - apt
  - ste
  - floor
  11c:
  - city_or_town
  11d:
  - state
  11e:
  - zipcode
  11f:
  - province
  11g:
  - postalcode
  11h:
  - country
  section_description_5:
  - Other Address and Contact Information
  12a:
  - street_number_and_name
  12b:
  - apt
  - ste
  - floor
  12c:
  - city_or_town
  12d:
  - state
  12e:
  - zipcode
  13a:
  - street_number_and_name
  13b:
  - apt
  - ste
  - floor
  13c:
  - city_or_town
  13d:
  - province
  13e:
  - postalcode
  13f:
  - country
  14:
  - daytime_telephone_number
  15:
  - mobile_telephone_number
  16:
  - email_address
  section_description_6:
  - Beneficiary's Marital Information
  17:
  - number_of_times_married
  18:
  - marital_status
  19:
  - date_of_current_marriage
  section_description_7:
  - Place of Beneficiary's Current Marriage (if married)
  20a:
  - city_or_town
  20b:
  - state
  20c:
  - province
  20d:
  - country
  section_description_8:
  - Names of Beneficiary's Spouses (if any)
  21a:
  - last_name
  21b:
  - first_name
  21c:
  - middle_name
  22:
  - date_marriage_ended
  23a:
  - last_name
  23b:
  - first_name
  23c:
  - middle_name
  24:
  - date_marriage_ended
  section_description_9:
  - Information About Beneficiary's Family
  25a:
  - last_name
  25b:
  - first_name
  25c:
  - middle_name
  26:
  - relationship
  27:
  - dob
  28:
  - country_of_birth
  29a:
  - last_name
  29b:
  - first_name
  29c:
  - middle_name
  30:
  - relationship
  31:
  - dob
  32:
  - country_of_birth
  33a:
  - last_name
  33b:
  - first_name
  33c:
  - middle_name
  34:
  - relationship
  35:
  - dob
  36:
  - country_of_birth
  37a:
  - last_name
  37b:
  - first_name
  37c:
  - middle_name
  38:
  - relationship
  39:
  - dob
  40:
  - country_of_birth
  41a:
  - last_name
  41b:
  - first_name
  41c:
  - middle_name
  42:
  - relationship
  43:
  - dob
  44:
  - country_of_birth
  section_description_10:
  - Beneficiary's Entry Information
  45:
  - ever_in_the_united_states
  46a:
  - class_of_admission
  46b:
  - i_94_record_number
  46c:
  - date_of_arrival
  46d:
  - date_of_expiry
  47:
  - passport_number
  48:
  - travel_document_number
  49:
  - country_of_passport_issuance
  50:
  - passport_or_travel_doc_expiration
  section_description_11:
  - Beneficiary's Employment Information
  51a:
  - current_employer
  51b:
  - street_number_and_name
  51c:
  - apt
  - ste
  - floor
  51d:
  - city_or_town
  51e:
  - state
  51f:
  - zipcode
  51g:
  - province
  51h:
  - postalcode
  51i:
  - country
  52:
  - date_employment_began
  section_description_12:
  - Additional Information About Beneficiary
  53:
  - ever_in_immigration_proceedings
  54:
  - type_of_proceedings
  55a:
  - city_or_town
  55b:
  - state
  56:
  - date
  57a:
  - last_name
  57b:
  - first_name
  57c:
  - middle_name
  58a:
  - street_number_and_name
  58b:
  - apt
  - ste
  - floor
  58c:
  - city_or_town
  58d:
  - province
  58e:
  - postalcode
  58f:
  - country
  59a:
  - street_number_and_name
  59b:
  - apt
  - ste
  - floor
  59c:
  - city_or_town
  59d:
  - state
  59e:
  - zipcode
  59f:
  - province
  59h:
  - country
  60a:
  - date_from
  60b:
  - date_to
  61a:
  - city_or_town
  61b:
  - state
  62a:
  - city_or_town
  62b:
  - province
  62c:
  - country
part_5:
  description:
  - Other Information
  1:
  - previously_filed
  2a:
  - last_name
  2b:
  - first_name
  2c:
  - middle_name
  3a:
  - city_or_town
  3b:
  - state
  4:
  - date_filed
  5:
  - result
  6a:
  - last_name
  6b:
  - first_name
  6c:
  - middle_name
  7:
  - relationship
  8a:
  - last_name
  8b:
  - first_name
  8c:
  - middle_name
  9:
  - relationship
part_6:
  description:
  - Petitioners Statement, Contact Information, Declaration, and Signature
  section_description_1:
  - Petitioner's Statement
  1a:
  - understand_english
  1b:
  - language_if_not_english
  2:
  - preparer_in_part_8
  section_description_3:
  - Petitioner's Contact Information
  3:
  - petitioner_day_telephone
  4:
  - petitioner_mbile_telephone
  5:
  - petitioner_email_address
  section_description_4:
  - Petitioner's Declaration and Certification
  section_description_5:
  - Petitioner's Signature
  6a:
  - petitioner_sign_in_ink
  6b:
  - date_of_signature
part_7:
  description:
  - Interpreter's Contact Information, Certification, and Signature
  section_description_1:
  - Intepreter's Full Name
  1a:
  - interpreter_last_name
  1b:
  - interpreter_first_name
  2:
  - interpreter_business_or_org_name
  section_description_2:
  - Interpreter's Mailing Address
  3a:
  - street_number_and_name
  3b:
  - apt
  - ste
  - floor
  3c:
  - city_or_town
  3d:
  - state
  3e:
  - zipcode
  3f:
  - province
  3h:
  - country
  section_description_3:
  - Interpreter's Contact Information
  4:
  - interpreters_day_time_telephone
  5:
  - interpreters_mobile_telephone
  6:
  - interpreters_email_address
  section_description_4:
  - Interpreter's Certification
  section_description_5:
  - Interpreter's Certification
  section_description_6:
  - Interpreter's Signature
  7:
  - interpreter_second_language
  7a:
  - interpreters_signature
  7b:
  - date_of_signature
part_8:
  description:
  - Contact Information, Declaration, and Signature of the Person Preparing this Petition, if Other Than the Petitioner
  section_description_1:
  - Preparer's Full Name
  1a:
  - preparers_last_name
  1b:
  - preparers_first_name
  2:
  - preparers_business_or_org_name
  section_description_2:
  - Preparer's Mailing Address
  3a:
  - street_number_and_name
  3b:
  - apt
  - ste
  - floor
  3c:
  - city_or_town
  3d:
  - state
  3e:
  - zipcode
  3f:
  - province
  3h:
  - country
  section_description_3:
  - Preparer's Contact Information
  4:
  - preparers_day_time_telephone
  5:
  - preparers_mobile_telephone
  6:
  - preparers_email_address
  section_description_4:
  - Preparer's Statement
  7a:
  - preparer_not_an_attorney
  7b:
  - preparer_is_an_attorney
  section_description_5:
  - Preparer's Certification
  section_description_6:
  - Preparer's Signature
  8a:
  - preparers_signature
  8b:
  - date_of_signature
part_9:
  description:
  - Additional Information
  1a:
  - last_name
  1b:
  - first_name
  1c:
  - middle_name
  2:
  - a_number
  3a:
  - page_number
  3b:
  - part_number
  3c:
  - item_number
  3d:
  - free_lines
  4a:
  - page_number
  4b:
  - part_number
  4c:
  - item_number
  4d:
  - free_lines
  5a:
  - page_number
  5b:
  - part_number
  5c:
  - item_number
  5d:
  - free_lines
  6a:
  - page_number
  6b:
  - part_number
  6c:
  - item_number
  6d:
  - free_lines
  7a:
  - page_number
  7b:
  - part_number
  7c:
  - item_number
  7d:
  - free_lines
