part_1:
  description:
  - Relationship (You are the Petitioner. Your relative is the Beneficiary)
  1:
  - I am filing this petition for my (Select only one box)
  - Spouse
  - Parent
  - Brother/Sister
  - Child
  2:
  - If you are filing this petition for your child or parent, select the box that describes your relationship (Select only one box)
  - child_married_parents
  - stepchild/stepparent
  - child_unmarried_parents
  - child_adopted
  3:
  - If the beneficiary is your brother/sister, are you related by adoption?
  - yes
  - no
  4:
  - Did you gain lawful permanent resident status or citizenship through adoption?
  - yes
  - no

part_2:
  part_description:
  - Information About You (Petitioner)
  1:
  - Alien Registration Number(A-Number)(if any)
  - alien_registration_number
  2:
  - USCIS Online Account Number (if any)
  - uscis_account_number
  3:
  - U.S. Social Security Number (if any)
  - ssn
  section_description_1:
  - Your Full Name
  4a:
  - Family Name (Last Name)
  - last_name
  4b:
  - Given Name (First Name)
  - first_name
  4c:
  - Middle Name
  - middle_name
  section_description_2:
  - Other Names Used (if any)
  5a:
  - Family Name (Last Name)
  - last_name
  5b:
  - Given Name (First Name)
  - first_name
  5c:
  - Middle Name
  - middle_name
  section_description_3:
  - Other Information
  6:
  - City/Town/Village of Birth
  - city_town_village_of_birth
  7:
  - Country of Birth
  - country_of_birth
  8:
  - Date of Birth (mm/dd/yyyy)
  - dob_mm_dd_yyyy
  9:
  - Sex
  - male
  - female
  section_description_4:
  - Mailing Address
  10a:
  - In Care Of Name
  - in_care_of_name
  10b:
  - Street Number and Name
  - street_number_and_name
  10c:
  - Apartment
  - Suite
  - Floor
  - Value
  10d:
  - City or Town
  - city_or_town
  10e:
  - State
  - state
  10f:
  - ZIP Code
  - zipcode
  10g:
  - Province
  - province
  10h:
  - Postal Code
  - postalcode
  10i:
  - Country
  - country
  11:
  - Is your current mailing address the same as your physical address?
  - yes
  - no
  section_description_5:
  - Address History
  12a:
  - Street Number and Name
  - street_number_and_name
  12b:
  - Apartment
  - Suite
  - Floor
  - Value
  12c:
  - City or Town
  - city_or_town
  12d:
  - State
  - state
  12e:
  - ZIP Code
  - zipcode
  12f:
  - Province
  - province
  12g:
  - Postal Code
  - postalcode
  12h:
  - Country
  - country
  13a:
  - Date From (mm/dd/yyyy)
  - date_from
  13b:
  - Date To (mm/dd/yyyy)
  - date_to
  14a:
  - Street Number and Name
  - street_number_and_name
  14b:
  - Apartment
  - Suite
  - Floor
  - Value
  14c:
  - City or Town
  - city_or_town
  14d:
  - State
  - state
  14e:
  - ZIP Code
  - zipcode
  14f:
  - Province
  - province
  14g:
  - Postal Code
  - postalcode
  14h:
  - Country
  - country
  15a:
  - Date From (mm/dd/yyyy)
  - date_from
  15b:
  - Date To (mm/dd/yyyy)
  - date_to
  section_description_6:
  - Your Marital Information
  16:
  - How Many Times Have You Been Married?
  - num_times_married
  17:
  - Single, Never Married
  - Married
  - Divorced
  - Widowed
  - Separated
  - Annulled
  18:
  - Date of Current Marriage (if currently married) (mm/dd/yyyy)
  - date_of_current_marriage
  section_description_7:
  - Place of Your Current Marriage (if married)
  19a:
  - City or Town
  - city_or_town
  19b:
  - State
  - state
  19c:
  - Province
  - province
  19d:
  - Country
  - country
  section_description_8:
  - Names of All Your Spouses, Spouse 1 first, then all prior (if any)
  20a:
  - Family Name (Last Name)
  - last_name
  20b:
  - Given Name (First Name)
  - first_name
  20c:
  - Middle Name
  - middle_name
  21:
  - Date Marriage Ended (mm/dd/yyyy)
  - date_marriage_ended
  22a:
  - Family Name (Last Name)
  - last_name
  22b:
  - Given Name (First Name)
  - first_name
  22c:
  - Middle Name
  - middle_name
  23:
  - Date Marriage Ended (mm/dd/yyyy)
  - date_marriage_ended
  section_description_9:
  - Information About Your Parents
  24a:
  - Family Name (Last Name)
  - last_name
  24b:
  - Given Name (First Name)
  - first_name
  24c:
  - Middle Name
  - middle_name
  25:
  - Date of Birth (mm/dd/yyyy)
  - dob
  26:
  - Sex
  - male
  - female
  27:
  - Country of Birth
  - country_of_birth
  28:
  - City/Town/Village of Residence
  - city_town_village_of_residence
  29:
  - Country of Residence
  - country_of_residence
  30a:
  - Family Name (Last Name)
  - last_name
  30b:
  - Given Name (First Name)
  - first_name
  30c:
  - Middle Name
  - middle_name
  31:
  - Date of Birth (mm/dd/yyyy)
  - dob
  32:
  - Sex
  - male
  - female
  33:
  - Country of Birth
  - country_of_birth
  34:
  - City/Town/Village or Residence
  - city_town_village_of_residence
  35:
  - Country of Residence
  - country_of_residence
  section_description_10:
  - Additional Information About You (Petitioner)
  36:
  - Select if Citizen or Permanent Resident (Select only one box)
  - us_citizen
  - lawful_permanent_resident
  37:
  - My citizenship was acquired through (Select only one box)
  - birth_in_the_us
  - naturalization
  - parents
  38:
  - Have you obtained a Certificate of naturalization or a Certificate of Citizenship
  - yes
  - no
  39a:
  - Certificate Number
  - certificate_number
  39b:
  - Place of Issuance
  - place_of_issuance
  39c:
  - Date of Issuance (mm/dd/yyyy)
  - date_of_issuance
  40a:
  - Class of Admission
  - class_of_admission
  40b:
  - Date of Admission (mm/dd/yyyy)
  - date_of_admission
  40c:
  - City or Town
  - city_or_town
  40d:
  - State
  - state
  41:
  - Did you gain lawful permanent resident status through marriage to a U.S. citizen or lawful permanent resident?
  - yes
  - no
  section_description_11:
  - Employment History
  42:
  - Name of Employer/Company
  - name_of_employer_company
  43a:
  - Street Number and Name
  - street_number_and_name
  43b:
  - Apartment
  - Suite
  - Floor
  - Value
  43c:
  - City or Town
  - city_or_town
  43d:
  - State
  - state
  43e:
  - ZIP Code
  - zipcode
  43f:
  - Province
  - province
  43g:
  - Postal Code
  - postalcode
  43h:
  - Country
  - country
  44:
  - Your Occupation
  - your_occupation
  45a:
  - Date From (mm/dd/yyyy)
  - date_from
  45b:
  - Date To (mm/dd/yyyy)
  - date_to
  46:
  - Name of Employer/Company
  - name_of_employer_company
  47a:
  - Street Number and Name
  - street_number_and_name
  47b:
  - Apartment
  - Suite
  - Floor
  - Value
  47c:
  - City or Town
  - city_or_town
  47d:
  - State
  - state
  47e:
  - ZIP Code
  - zipcode
  47f:
  - Province
  - province
  47g:
  - Postal Code
  - postalcode
  47h:
  - Country
  - country
  48:
  - Your Occupation
  - your_occupation
  49a:
  - Date From (mm/dd/yyyy)
  - date_from
  49b:
  - Date To (mm/dd/yyyy)
  - date_to
part_3:
  description:
  - Biographic Information
  1:
  - Ethnicity Select (Select only one box)
  - Hispanic or Latino
  - Not Hispanic or Latino
  2:
  - Race (Select all applicable boxes)
  - White
  - Asian
  - Black or African American
  - American Indian or Alaska Native
  - Native Hawaiiwan or Other Pacific Islander
  3:
  - Height
  - Feet
  - Inches
  4:
  - Weight
  - Pounds
  5:
  - Eye Color
  - Black
  - Blue
  - Brown
  - Gray
  - Green
  - Hazel
  - Maroon
  - Pink
  - Unknown/Other
  6:
  - Hair Color (Select only one box)
  - Bald (No hair)
  - Black
  - Blond
  - Brown
  - Gray
  - Red
  - Sandy
  - White
  - Unknown/Other
part_4:
  description:
  - Information About Beneficiary
  1:
  - Alient Registration Number (A-Number) (if any)
  - alien_registration_number
  2:
  - USCIS Online Account Number (if any)
  - uscis_account_number
  3:
  - U.S. Social Security Number (if any)
  - ssn
  section_description_1:
  - Beneficiary's Full Name
  4a:
  - Family Name (Last Name)
  - last_name
  4b:
  - Given Name (First Name)
  - first_name
  4c:
  - Middle Name
  - middle_name
  section_description_2:
  - Other Names Used (if any)
  5a:
  - Family Name (Last Name)
  - last_name
  5b:
  - Given Name (First Name)
  - first_name
  5c:
  - Middle Name
  - middle_name
  section_description_3:
  - Other Information About Beneficiary
  6:
  - City/Town/Village of Birth
  - city_town_village_of_birth
  7:
  - Country of Birth
  - country_of_birth
  8:
  - Date of Birth (mm/dd/yyyy)
  - dob_mm_dd_yyyy
  9:
  - Sex
  - sex
  10:
  - Has anyone else ever filed a petition for the beneficiary?
  - yes
  - no
  - Unknown
  section_description_4:
  - Beneficiary's Physical Address
  11a:
  - Street Number and Name
  - street_number_and_name
  11b:
  - Apartment
  - Suite
  - Floor
  - Value
  11c:
  - City or Town
  - city_or_town
  11d:
  - State
  - state
  11e:
  - ZIP Code
  - zipcode
  11f:
  - Province
  - province
  11g:
  - Postal Code
  - postalcode
  11h:
  - Country
  - country
  section_description_5:
  - Other Address and Contact Information
  12a:
  - Street Number and Name
  - street_number_and_name
  12b:
  - Apartment
  - Suite
  - Floor
  - Value
  12c:
  - City or Town
  - city_or_town
  12d:
  - State
  - state
  12e:
  - ZIP Code
  - zipcode
  13a:
  - Street Number and Name
  - street_number_and_name
  13b:
  - Apartment
  - Suite
  - Floor
  - Value
  13c:
  - City or Town
  - city_or_town
  13d:
  - Province
  - province
  13e:
  - Postal Code
  - postalcode
  13f:
  - Country
  - country
  14:
  - Daytime Telephone Number (if any)
  - daytime_telephone_number
  15:
  - Mobile Telephone Number (if any)
  - mobile_telephone_number
  16:
  - Email Address (if any)
  - email_address
  section_description_6:
  - Beneficiary's Marital Information
  17:
  - How many times has the beneficiary been married?
  - number_of_times_married
  18:
  - Current Marital status
  - Single, Never Married
  - Married
  - Divorced
  - Widowed
  - Separated
  - Annulled
  - Date of Current Marriage (if currently married) (mm/dd/yyyy)
  19:
  - Date of Current Marriage (if currently married)
  - date_of_current_marriage
  section_description_7:
  - Place of Beneficiary's Current Marriage (if married)
  20a:
  - city_or_town
  20b:
  - state
  20c:
  - province
  20d:
  - country
  section_description_8:
  - Names of Beneficiary's Spouses (if any)
  21a:
  - last_name
  21b:
  - first_name
  21c:
  - middle_name
  22:
  - date_marriage_ended
  23a:
  - last_name
  23b:
  - first_name
  23c:
  - middle_name
  24:
  - date_marriage_ended
  section_description_9:
  - Information About Beneficiary's Family
  25a:
  - last_name
  25b:
  - first_name
  25c:
  - middle_name
  26:
  - relationship
  27:
  - dob
  28:
  - country_of_birth
  29a:
  - last_name
  29b:
  - first_name
  29c:
  - middle_name
  30:
  - relationship
  31:
  - dob
  32:
  - country_of_birth
  33a:
  - last_name
  33b:
  - first_name
  33c:
  - middle_name
  34:
  - relationship
  35:
  - dob
  36:
  - country_of_birth
  37a:
  - last_name
  37b:
  - first_name
  37c:
  - middle_name
  38:
  - relationship
  39:
  - dob
  40:
  - country_of_birth
  41a:
  - last_name
  41b:
  - first_name
  41c:
  - middle_name
  42:
  - relationship
  43:
  - dob
  44:
  - country_of_birth
  section_description_10:
  - Beneficiary's Entry Information
  45:
  - ever_in_the_united_states
  46a:
  - class_of_admission
  46b:
  - i_94_record_number
  46c:
  - date_of_arrival
  46d:
  - date_of_expiry
  47:
  - passport_number
  48:
  - travel_document_number
  49:
  - country_of_passport_issuance
  50:
  - passport_or_travel_doc_expiration
  section_description_11:
  - Beneficiary's Employment Information
  51a:
  - current_employer
  51b:
  - street_number_and_name
  51c:
  - Apartment
  - Suite
  - Floor
  - Value
  51d:
  - city_or_town
  51e:
  - state
  51f:
  - zipcode
  51g:
  - province
  51h:
  - postalcode
  51i:
  - country
  52:
  - date_employment_began
  section_description_12:
  - Additional Information About Beneficiary
  53:
  - ever_in_immigration_proceedings
  54:
  - type_of_proceedings
  55a:
  - city_or_town
  55b:
  - state
  56:
  - date
  57a:
  - last_name
  57b:
  - first_name
  57c:
  - middle_name
  58a:
  - street_number_and_name
  58b:
  - Apartment
  - Suite
  - Floor
  - Value
  58c:
  - city_or_town
  58d:
  - province
  58e:
  - postalcode
  58f:
  - country
  59a:
  - street_number_and_name
  59b:
  - Apartment
  - Suite
  - Floor
  - Value
  59c:
  - city_or_town
  59d:
  - state
  59e:
  - zipcode
  59f:
  - province
  59h:
  - country
  60a:
  - date_from
  60b:
  - date_to
  61a:
  - city_or_town
  61b:
  - state
  62a:
  - city_or_town
  62b:
  - province
  62c:
  - country
part_5:
  description:
  - Other Information
  1:
  - previously_filed
  2a:
  - last_name
  2b:
  - first_name
  2c:
  - middle_name
  3a:
  - city_or_town
  3b:
  - state
  4:
  - date_filed
  5:
  - result
  6a:
  - last_name
  6b:
  - first_name
  6c:
  - middle_name
  7:
  - relationship
  8a:
  - last_name
  8b:
  - first_name
  8c:
  - middle_name
  9:
  - relationship
part_6:
  description:
  - Petitioners Statement, Contact Information, Declaration, and Signature
  section_description_1:
  - Petitioner's Statement
  1a:
  - understand_english
  1b:
  - language_if_not_english
  2:
  - preparer_in_part_8
  section_description_3:
  - Petitioner's Contact Information
  3:
  - petitioner_day_telephone
  4:
  - petitioner_mbile_telephone
  5:
  - petitioner_email_address
  section_description_4:
  - Petitioner's Declaration and Certification
  section_description_5:
  - Petitioner's Signature
  6a:
  - petitioner_sign_in_ink
  6b:
  - date_of_signature
part_7:
  description:
  - Interpreter's Contact Information, Certification, and Signature
  section_description_1:
  - Intepreter's Full Name
  1a:
  - interpreter_last_name
  1b:
  - interpreter_first_name
  2:
  - interpreter_business_or_org_name
  section_description_2:
  - Interpreter's Mailing Address
  3a:
  - street_number_and_name
  3b:
  - Apartment
  - Suite
  - Floor
  - Value
  3c:
  - city_or_town
  3d:
  - state
  3e:
  - zipcode
  3f:
  - province
  3h:
  - country
  section_description_3:
  - Interpreter's Contact Information
  4:
  - interpreters_day_time_telephone
  5:
  - interpreters_mobile_telephone
  6:
  - interpreters_email_address
  section_description_4:
  - Interpreter's Certification
  section_description_5:
  - Interpreter's Certification
  section_description_6:
  - Interpreter's Signature
  7:
  - interpreter_second_language
  7a:
  - interpreters_signature
  7b:
  - date_of_signature
part_8:
  description:
  - Contact Information, Declaration, and Signature of the Person Preparing this Petition, if Other Than the Petitioner
  section_description_1:
  - Preparer's Full Name
  1a:
  - preparers_last_name
  1b:
  - preparers_first_name
  2:
  - preparers_business_or_org_name
  section_description_2:
  - Preparer's Mailing Address
  3a:
  - street_number_and_name
  3b:
  - Apartment
  - Suite
  - Floor
  - Value
  3c:
  - city_or_town
  3d:
  - state
  3e:
  - zipcode
  3f:
  - province
  3h:
  - country
  section_description_3:
  - Preparer's Contact Information
  4:
  - preparers_day_time_telephone
  5:
  - preparers_mobile_telephone
  6:
  - preparers_email_address
  section_description_4:
  - Preparer's Statement
  7a:
  - preparer_not_an_attorney
  7b:
  - preparer_is_an_attorney
  section_description_5:
  - Preparer's Certification
  section_description_6:
  - Preparer's Signature
  8a:
  - preparers_signature
  8b:
  - date_of_signature
part_9:
  description:
  - Additional Information
  1a:
  - last_name
  1b:
  - first_name
  1c:
  - middle_name
  2:
  - a_number
  3a:
  - page_number
  3b:
  - part_number
  3c:
  - item_number
  3d:
  - free_lines
  4a:
  - page_number
  4b:
  - part_number
  4c:
  - item_number
  4d:
  - free_lines
  5a:
  - page_number
  5b:
  - part_number
  5c:
  - item_number
  5d:
  - free_lines
  6a:
  - page_number
  6b:
  - part_number
  6c:
  - item_number
  6d:
  - free_lines
  7a:
  - page_number
  7b:
  - part_number
  7c:
  - item_number
  7d:
  - free_lines
